apiVersion: v1
kind: Service
metadata:
  name: myphp-services
spec:
  type: NodePort
  selector:
    app: myphp 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110
